# This is a basic workflow to help you get started with Actions

name: "Airflow CI"
on:
  push:
    branches: 
      - master
jobs:
  deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout 
          uses: actions/checkout@v3
        - name: Run command on remote 
          uses: fifsky/ssh-action@master
          with:
            host: ${{secrets.HOST}}
            port: ${{secrets.PORT}}
            user: ${{secrets.USER}}
            private_key: ${{secrets.KEY}}
            fingerprint: ${{secrets.FINGERPRINT}}
            script: |
              mkdir /home/airflowpipeline
              touch file.txt
              git checkout master
              git pull origin master
